---

- name: Add ingress-nginx chart repo
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Deploy nginx controller
  community.kubernetes.helm:
    name: nginx-ingress
    release_state: "{{ state }}"
    chart_version: "3.10.1"
    chart_ref: ingress-nginx/ingress-nginx
    create_namespace: true
    update_repo_cache: true
    release_namespace: "{{ nginx_namespace }}"
    wait: yes
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"

- name: Delete namespace
  when: state == "absent"
  community.kubernetes.k8s:
    name: "{{ nginx_namespace }}"
    api_version: v1
    kind: Namespace
    state: "{{ state }}"