apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: "{{ observability_namespace }}"
  labels:
    grafana_datasource: "true"
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:
    - name: Prometheus
      uid: 1
      type: prometheus
      url: http://prometheus-server:9090
      access: proxy
      isDefault: true
    - name: Loki
      uid: 2
      type: loki
      url: http://loki:3100
    - name: Redis
      uid: 3
      type: redis-datasource
      url: redis://redis-master.redis:6379
      secureJsonData:
        password: "{{ redis_password }}"
      jsonData:
        poolSize: 5
        timeout: 10
        pingInterval: 0
        pipelineWindow: 0
    - name: Prometheus AlertManager
      uid: 4
      type: camptocamp-prometheus-alertmanager-datasource
      url: http://prometheus-alertmanager.{{ observability_namespace }}{{ observability_subpathAlertmanager }}