apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notifier
  namespace: "{{ observability_namespace }}"
  labels:
    grafana_notifier: "true"
data:
  notifier.yaml: |-
    notifiers:
    - name: notification-channel
      type: prometheus-alertmanager
      uid: 1
      org_name: Main Org.
      is_default: true
      send_reminder: false
      frequency: 1h
      disable_resolve_message: false
      settings:
        uploadImage: true
        url: "http://prometheus-alertmanager.{{ observability_namespace }}{{ observability_subpathAlertmanager }}"
    delete_notifiers: