{
 "title": "Dapr / System Services Dashboard",
 "tags": [ "dapr" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Health & Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{app=~\"dapr-sentry|dapr-placement|dapr-sidecar-injector|dapr-operator\"}) by (app)",
     "legendFormat": "{{ '{{app}}' }}"
    }
   ]
  },
  {
   "title": "Total CPU usage (kernel and user)",
   "type": "graph",
   "description": "This shows total amount of kernel and user CPU usage time.",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"(dapr-sentry|dapr-sidecar-injector|dapr-placement|dapr-operator).*\"}[5m])) by (pod)",
     "legendFormat": "{{ '{{pod}}' }}"
    }
   ]
  },
  {
   "title": "Memory usage in bytes",
   "type": "graph",
   "description": "The amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{app=~\"(dapr-sentry|dapr-sidecar-injector|dapr-placement|dapr-operator)\"}) by (app)",
     "legendFormat": "{{ '{{app}}' }}"
    }
   ]
  },
  {
   "title": "Number of GO routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(go_goroutines{app=~\"(dapr-sentry|dapr-sidecar-injector|dapr-placement|dapr-operator)\"}) by (app)",
     "legendFormat": "{{ '{{app}}' }}"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "# Services Created",
   "type": "graph",
   "description": "The total number of services created.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(dapr_operator_service_created_total) by (app_id)",
     "legendFormat": "{{ '{{app_id}}' }}"
    }
   ]
  },
  {
   "title": "# Services Deleted",
   "type": "graph",
   "description": "The total number of services deleted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_operator_service_deleted_total",
     "legendFormat": "{{ '{{app_id}}' }}"
    }
   ]
  },
  { "title": "Sidecar Injector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "# sidecar injection requests",
   "type": "graph",
   "description": "The total number of sidecar injection requests.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_injector_sidecar_injection_requests_total",
     "legendFormat": "sidecars requests"
    }
   ]
  },
  {
   "title": "# successful sidecar injected",
   "type": "graph",
   "description": "The total number of successful sidecar injection requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_injector_sidecar_injection_succeeded_total",
     "legendFormat": "{{ '{{app_id}}' }}"
    }
   ]
  },
  { "title": "CA Sentry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Root/Issuer cert expiry",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(dapr_sentry_issuercert_expiry_timestamp) - time()"
    }
   ]
  },
  {
   "title": "Certificate Signing Requests (CSR) from Daprd",
   "type": "graph",
   "description": "Certificate Signing Request ( CSR ) from Dapr runtime",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_cert_sign_request_received_total{app=\"dapr-sentry\"})",
     "legendFormat": "CSR Requests"
    },
    {
     "expr": "sum(dapr_sentry_cert_sign_success_total{app=\"dapr-sentry\"})",
     "legendFormat": "CSR Success"
    },
    {
     "expr": "sum(dapr_sentry_cert_sign_failure_total{app=\"dapr-sentry\"})",
     "legendFormat": "CSR Failure"
    }
   ]
  },
  {
   "title": "CSR Failures",
   "type": "graph",
   "description": "This chart shows the failure reason of Certificate Sign Request.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_cert_sign_failure_total{app=\"dapr-sentry\"}) by (reason)",
     "legendFormat": "{{ '{{reason}}' }}"
    }
   ]
  },
  {
   "title": "Issuer cert and key changed total",
   "type": "graph",
   "description": "This will be counted when issuer cert and key are changed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_issuercert_changed_total{app=\"dapr-sentry\"})"
    }
   ]
  },
  {
   "title": "Server TLS certificate issuance failures",
   "type": "graph",
   "description": "This chart shows the reason of gRPC server TLS certificate issuance failures.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_servercert_issue_failed_total{app=\"dapr-sentry\"}) by (reason)",
     "legendFormat": "{{ '{{reason}}' }}"
    }
   ]
  },
  { "title": "Placement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "# total replicas",
   "type": "graph",
   "description": "The total number of replicas connected to placement service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dapr_placement_hosts_total", "legendFormat": "hosts" }
   ]
  },
  {
   "title": "# replicas not hosting actors",
   "type": "graph",
   "description": "The total number of replicas which are not hosting actors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_placement_nonactorhosts_total",
     "legendFormat": "{{ '{{kubernetes_pod_name}}' }}"
    }
   ]
  },
  {
   "title": "# actor types",
   "type": "graph",
   "description": "The total number of actor types registered with Dapr runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_placement_actortypes_total",
     "legendFormat": "actor types"
    }
   ]
  }
 ]
}