{
 "title": "Dapr / Actor Dashboard",
 "description": "This is the dashboard for Dapr Actor",
 "tags": [ "dapr" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "NAMESPACE",
    "query": "label_values(dapr_runtime_component_loaded,kubernetes_namespace)"
   },
   {
    "name": "dapr_actor_type",
    "label": "ACTOR TYPE",
    "query": "label_values(dapr_runtime_actor_pending_actor_calls,actor_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput/latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actor API Latency (App->Dapr) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the turn-around latency when user app calls Dapr Actor API. For example, you can understand each statestore and service invocation performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_http_server_latency_bucket{path=~\"/v1.0/actors/$dapr_actor_type/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[95p] {{ '{{method}}' }} {{ '{{path}}' }} ({{ '{{app_id}}' }})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_http_server_latency_bucket{path=~\"/v1.0/actors/$dapr_actor_type/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[75p] {{ '{{method}}' }} {{ '{{path}}' }} ({{ '{{app_id}}' }})"
      }
     ]
    },
    {
     "title": "Actor API request rate (App -> Dapr) (RPS)",
     "type": "graph",
     "description": "This charts shows completed request rate (rps) when User app calls Dapr Actor APIs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, method, path) (rate(dapr_http_server_response_count{path=~\"/v1.0/actors/$dapr_actor_type/.*\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{ '{{method}}' }} {{ '{{path}}' }} ({{ '{{app_id}}' }})"
      }
     ]
    },
    {
     "title": "Actor Callback latency (Dapr -> App) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the inbound request latency from Dapr to App. You can analyze App's API endpoint performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_http_client_roundtrip_latency_bucket{path=~\"actors/$dapr_actor_type/.*/method/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[95p] {{ '{{method}}' }} /{{ '{{path}}' }} ({{ '{{app_id}}' }})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_http_client_roundtrip_latency_bucket{path=~\"actors/$dapr_actor_type/.*/method/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[75p] {{ '{{method}}' }} /{{ '{{path}}' }} ({{ '{{app_id}}' }})"
      }
     ]
    },
    {
     "title": "Actor Callback request rate (Dapr -> App) (RPS)",
     "type": "graph",
     "description": "This charts shows request rate (rps) when Dapr runtime calls User app HTTP endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, method, path) (rate(dapr_http_client_completed_count{path=~\"actors/$dapr_actor_type/.*/method/.*\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{ '{{method}}' }} {{ '{{path}}' }} ({{ '{{app_id}}' }})"
      }
     ]
    }
   ]
  },
  { "title": "Timer & Reminder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Actor timer trigger",
   "type": "graph",
   "description": "Timer trigger status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dapr_http_client_roundtrip_latency_bucket{path=~\"actors/$dapr_actor_type/.*/method/timer/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (path)",
     "legendFormat": "{{ '{{path}}' }}"
    }
   ]
  },
  {
   "title": "Actor reminder trigger",
   "type": "graph",
   "description": "Reminder trigger status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dapr_http_client_roundtrip_latency_bucket{path=~\"actors/$dapr_actor_type/.*/method/remind/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (path)",
     "legendFormat": "{{ '{{path}}' }}"
    }
   ]
  },
  { "title": "Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pending locks Per Actor",
   "type": "graph",
   "description": "It contains the number of pending actor calls that are waiting to acquire the per-actor lock that enforces turn-based concurrency.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Pending Locks" }
   ],
   "targets": [
    {
     "expr": "dapr_runtime_actor_pending_actor_calls{actor_type=~\"$dapr_actor_type\"}",
     "legendFormat": "{{ '{{actor_type}}' }}.{{ '{{actor_id}}' }}"
    }
   ]
  }
 ]
}