---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: observability,test
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: observability,test
  name: tls-domain-certificate
  namespace: "{{ certificate_namespace }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ certificate_tlscrt_base64 }}
  tls.key: {{ certificate_tlskey_base64 }}
